### ISSUE TITLE
[bug] filter with a variable does not get applied to a sql metric using soda cli

### ISSUE THREAD

**Issue by lgov** [sodadata/soda-sql#114]
**Describe the bug**
I have a data set with panel data from multiple data sources: multiple columns with new records appended every week. Every time new data gets appended from one data source, I want to check the data quality for that single data source.
The goal is to include this in Airflow+alerting so that the context of the error is already clear to the person handling the alert.

Ideally I have one scan file with metrics that can take a parameter so that I can use the same file for each data source separately.

This should be possible with the filtering feature (*) but there are two problems:
1. The documentation mentions that this feature doesn't work yet with the CLI
2. The feature indeed doesn't work for me, the query is logged but without the WHERE clause that the filter is supposed to add to the query.

I say these are two problems because Vijay told me on Slack that despite the doc warning this is supposed to work already.

(*) https://docs.soda.io/soda-sql/documentation/filtering.html

**To Reproduce**
Take a dataset and use a sql metric with a filter as in my scan.yml file.
```
soda scan -v R_ID=15 warehouse.yml tables/scan.yml
```

**Context**
My scan.yml file:

```
table_name: xxx_view
filter: "r_id = {{ R_ID }}"
sql_metrics:
    - sql: |
        SELECT r_id, week, s_id, p_id, count(price) as prices_found
        FROM xxx_view
        GROUP BY r_id, week, s_id, p_id
        ORDER BY r_id, week, s_id, p_id
      group_fields:
        - r_id
        - week
        - s_id
        - p_id
      tests:
        - prices_found > 0
 ```

**OS**: Mac OS X
**Python Version**: Python 3.8.6
**Soda SQL Version**: main branch 
**Warehouse Type**: athena
