### ISSUE TITLE
[bug] Column isn't set when flushing sql_metric measurements

### ISSUE THREAD

**Issue by dirkgroenen** [sodadata/soda-sql#126]
**Describe the bug**

I'm having this scan-yml which contains custom SQL metrics on a column level. I'm expecting those custom SQL metrics to generate Custom Metric Measurements which are associated with the belonging column, but when measurements are flushed the column isn't send to the platform.

See the following snippet, where you can see that `sodaSQlScanMeasurements` doesn't contain the column, even though it does belong to `O_ORDERSTATUS`. 

```
 | Executing SQL query: 
SELECT
  COUNT(CASE WHEN O_ORDERSTATUS = 'P' THEN 1 END) as ORDER_P,
  COUNT(CASE WHEN O_ORDERSTATUS = 'O' THEN 1 END) as ORDER_O
FROM ORDERS

  | SQL took 0:00:00.107177
  | SQL metric O_ORDERSTATUS.sql_metric[0] ORDER_P -> 38543
  | Query measurement: ORDER_P = 38543
  | SQL metric O_ORDERSTATUS.sql_metric[0] ORDER_O -> 732044
  | Query measurement: ORDER_O = 732044
  | > /api/command {
  "type": "sodaSqlScanMeasurements",
  "scanReference": "92276c91-1afe-4b68-861f-6b4bba046ddf",
  "measurements": [
    {
      "metric": "ORDER_P",
      "value": 38543
    },
    {
      "metric": "ORDER_O",
      "value": 732044
    }
  ]
}
  | < 200 {
  "added": 2
}
```

**To Reproduce**
Execute a `soda scan` using the below `orders.yml` on a snowflake sample dataset. Make sure it's connected to the Soda Cloud so measurements are send. 

**Context**
`orders.yml`

```yml
table_name: ORDERS
metrics:
  - row_count
  - sum
  - missing_count
  - stddev
  - variance
  - avg_length
  - valid_count
  - distinct
  - histogram
  - mins
  - maxs
  - frequent_values
columns:
  O_TOTALPRICE:
    sql_metrics:
      - sql: |
          SELECT SUM(O_TOTALPRICE) as OPEN_TOTALPRICE FROM ORDERS WHERE O_ORDERSTATUS = 'O'
        tests:
          open_orders_price: OPEN_TOTALPRICE < 2000000

  O_ORDERSTATUS:
    valid_values:
      - O
      - F
    sql_metrics:
      - sql: |
          SELECT
            COUNT(CASE WHEN O_ORDERSTATUS = 'P' THEN 1 END) as ORDER_P,
            COUNT(CASE WHEN O_ORDERSTATUS = 'O' THEN 1 END) as ORDER_O
          FROM ORDERS
        tests:
          open_orders: ORDER_O == 0
          processing_orders: ORDER_P > 0

tests:
  dataset_size: row_count == 0

```

**OS**: Linux
**Python Version**: Python 3.8
**Soda SQL Version**: 2.0.0b15
**Warehouse Type**: Snowflake
