### ISSUE TITLE
[bug] Test is throwing exception because it can't serialize Decimal 

### ISSUE THREAD

**Issue by dirkgroenen** [sodadata/soda-sql#127]
**Describe the bug**
I have this test which tests the sum of a `NUMBER(12,2)` type column in Snowflake, but the test is throwing an exception:

```
    {
      "id": "{\"column\":\"O_TOTALPRICE\",\"sql_metric_index\":0,\"test_name\":\"open_orders_price\"}",
      "description": "column(O_TOTALPRICE) sqlmetric(0) open_orders_price(OPEN_TOTALPRICE < 2000000)",
      "expression": "OPEN_TOTALPRICE < 2000000",
      "columnName": "O_TOTALPRICE",
      "error": "Object of type Decimal is not JSON serializable"
    }
```

**To Reproduce**
Run a test with the `orders.yml` file as pasted below on the Snowflake sample dataset.

**Context**
`orders.yml`

```yml
table_name: ORDERS
metrics:
  - row_count
columns:
  O_TOTALPRICE:
    sql_metrics:
      - sql: |
          SELECT SUM(O_TOTALPRICE) as OPEN_TOTALPRICE FROM ORDERS WHERE O_ORDERSTATUS = 'O'
        tests:
          open_orders_price: OPEN_TOTALPRICE < 2000000
```

**OS**: Linux
**Python Version**: 3.8
**Soda SQL Version**: 2.0.0b15
**Warehouse Type**: Snowflake
