### ISSUE TITLE
[enhancement] It would be helpful to provide a filter(or custom query) to analyze a table

### ISSUE THREAD

**Issue by mmigdiso** [sodadata/soda-sql#136]
Currently soda analyze works on a small dataset to create the analyzer templates and it does it by applying a LIMIT clause to the table. 
Running analysis on a limited dataset might not always be a good idea. Let's say that I have a table containing data from 2010 and over 11 years some columns have changed the format. For example, the user_id was a hash code and we changed it to uuid.
Limit 1000 will always give the earliest 1000 rows (not guaranteed as a RDBMS standard but it is the way how it works on redshift). Extracting patterns based on the data that was generated 1000 years ago might not be accurate.

It would be very helpful to provide a way to let the data owner provide a query to be used for sampling. 
something like the following option in warehouse.yml would do the job. 

```
connection:
  type: redshift
  host:  HOST
  username: env_var(REDSHIFT_USERNAME)
  password: env_var(REDSHIFT_PASSWORD)
  region:  XXXX
  database: db
  schema: schema1
  analyze_templates:
    table1: "select * from table1 where id > 1000 limit 10"
```
