### ISSUE TITLE
[enhancement] We might want to include only/ exclude certain tables in the analyze phase

### ISSUE THREAD

**Issue by mmigdiso** [sodadata/soda-sql#138]
By default, soda fetches all of the tables and starts analyzing them. This is not always a wanted scenario. Specially if the schema has hundreds of tables some of which may not need to be covered by DQ. 

I propose having an include_tables/exclude_tables property in the warehouse.yml file. 
ex: 
```
name: redshift
connection:
  type: redshift
  host: testtest
  username: env_var(REDSHIFT_USERNAME)
  password: env_var(REDSHIFT_PASSWORD)
  region:  XXXX
  database: DB
  schema: test_schema
  tables_included:
    - table_to_be_included
```
