### ISSUE TITLE
scan results to json fails for group by sql_metrics

### ISSUE THREAD

**Issue by vanpeltj** [sodadata/soda-sql#158]
Exporting the scan_result object to_json fails when there is a group_by in the sql_metrics. Also, I had to convert a datetime field to a varchar as datetime fields cannot be serialized by default by json.

` ERROR - 'dict' object has no attribute 'to_json'
Traceback (most recent call last):
...
    print(scan_result.to_json())
  File "/usr/local/lib/python3.6/site-packages/sodasql/scan/scan_result.py", line 67, in to_json
    'measurements': [measurement.to_json() for measurement in self.measurements],
  File "/usr/local/lib/python3.6/site-packages/sodasql/scan/scan_result.py", line 67, in <listcomp>
    'measurements': [measurement.to_json() for measurement in self.measurements],
  File "/usr/local/lib/python3.6/site-packages/sodasql/scan/measurement.py", line 42, in to_json
    json['groupValues'] = [group_value.to_json() for group_value in self.group_values]
  File "/usr/local/lib/python3.6/site-packages/sodasql/scan/measurement.py", line 42, in <listcomp>
    json['groupValues'] = [group_value.to_json() for group_value in self.group_values]
AttributeError: 'dict' object has no attribute 'to_json'
`

**Context**
```yml sql_metrics:
sql_metrics:
    - sql: |
        SELECT
          CAST(reportingDate as varchar(250)) as reporting_date,
          sum(outstandingAmount) as outstandingAmount
        FROM someTable
        GROUP BY CAST(reportingDate as varchar(250))
      group_fields:
        - reporting_date
      tests:
        - outstandingAmount > 500000
 ```

**OS**: Ubuntu
**Python Version**: 3.6.12
**Soda SQL Version**: '2.0.0b20'
**Warehouse Type**: Microsoft SQL Server

**Comment by vijaykiran** [comment]
With soda-sql 2.1.0b3 couldn't reproduce with demo data, and `scan_result.to_json()` works as expected. @vanpeltj, please re-open if you still see this behaviour on latest version of Soda SQL.

here's the scan.yml
```yaml
table_name: demodata
sql_metrics:
  - sql: |
      SELECT country, sum(size) AS total_size FROM demodata
      GROUP BY country
    group_fields:
      - country
    tests:
      - total_size < 100
```

And here is the output:

```shell
soda scan warehouse.yml tables/vk_test.yml
  | 2.1.0b3
  | Scanning tables/vk_test.yml ...
  | No Soda Cloud account configured
  | Executing SQL query:
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE lower(table_name) = 'demodata'
  AND table_catalog = 'sodasql'
  AND table_schema = 'public'
  | SQL took 0:00:00.024198
  |   id (character varying)
  |   name (character varying)
  |   size (integer)
  |   date (date)
  |   feepct (character varying)
  |   country (character varying)
  | 6 columns:
  | Query measurement: schema = [{'name': 'id', 'type': 'character varying', 'dataType': 'character varying', 'nullable': True, 'semanticType': 'text'}, {'name': 'name', 'type': 'character varying', 'dataType': 'character varying', 'nullable': True, 'semanticType': 'text'}, {'name': 'size', 'type': 'integer', 'dataType': 'integer', 'nullable': True, 'semanticType': 'number'}, {'name': 'date', 'type': 'date', 'dataType': 'date', 'nullable': True, 'semanticType': 'time'}, {'name': 'feepct', 'type': 'character varying', 'dataType': 'character varying', 'nullable': True, 'semanticType': 'text'}, {'name': 'country', 'type': 'character varying', 'dataType': 'character varying', 'nullable': True, 'semanticType': 'text'}]
  | Executing SQL query:
SELECT country, sum(size) AS total_size FROM demodata
GROUP BY country

  | SQL took 0:00:00.002893
  | SQL metric sql_metric[0] total_size {'country': 'Netherlands'} -> 18735
  | Test sqlmetric(0) test(total_size < 100) failed with group values {'country': 'Netherlands'} with measurements {"total_size": 18735}
  | SQL metric sql_metric[0] total_size {'country': 'UK'} -> 113510
  | Test sqlmetric(0) test(total_size < 100) failed with group values {'country': 'UK'} with measurements {"total_size": 113510}
  | SQL metric sql_metric[0] total_size {'country': 'Spain'} -> 47475
  | Test sqlmetric(0) test(total_size < 100) failed with group values {'country': 'Spain'} with measurements {"total_size": 47475}
  | SQL metric sql_metric[0] total_size {'country': 'US'} -> 170279
  | Test sqlmetric(0) test(total_size < 100) failed with group values {'country': 'US'} with measurements {"total_size": 170279}
  | Query measurement: total_size:
  group{'country': 'Netherlands'} = 18735
  group{'country': 'UK'} = 113510
  group{'country': 'Spain'} = 47475
  group{'country': 'US'} = 170279
  | Executed 2 queries in 0:00:00.029821
  | Scan summary ------
  | 2 measurements computed
  | 4 tests executed
  | 4 of 4 tests failed:
  |   Test sqlmetric(0) test(total_size < 100) failed with group values {'country': 'Netherlands'} with measurements {"total_size": 18735}
  |   Test sqlmetric(0) test(total_size < 100) failed with group values {'country': 'UK'} with measurements {"total_size": 113510}
  |   Test sqlmetric(0) test(total_size < 100) failed with group values {'country': 'Spain'} with measurements {"total_size": 47475}
  |   Test sqlmetric(0) test(total_size < 100) failed with group values {'country': 'US'} with measurements {"total_size": 170279}
  | Exiting with code 1
```
