### ISSUE TITLE
Missing values without quotes

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-sql#160]
```
  resetinterval:
      valid_values: 
        - Widowed
        - Married
        - single
      missing_values:
        - 'N/A'
      tests:
        - missing_count == 0
        - invalid_count == 0
```

leads to

```
psycopg2.errors.UndefinedColumn: column "n" does not exist
LINE 107: ...T ("resetinterval" IS NULL OR "resetinterval" IN (N/A)) THEN...
```
