### ISSUE TITLE
Metric avg_length not functioning as expected

### ISSUE THREAD

**Issue by janet-can** [sodadata/soda-sql#18]
**Describe the bug**
In attempting to use avg_length metric in tests, I have been unable to get it to work, only failures with "not defined" error message.

**Context**
I have tried a few variations of the scan.yml to see if I could get it to work. Here are my attempts using the demodata from tutorial:

YAML1
```
columns:
  feepct:
    tests:
      - avg_length > 3
```

OUTPUT1
```
  | Test error for "avg_length > 3": name 'avg_length' is not defined
  | Executed 2 queries in 0:00:00.039690
  | Scan summary ------
  | 40 measurements computed
  | 1 tests executed
  | 1 of 1 tests failed:
  |   Test column(feepct) test(avg_length > 3) failed with metric values null
  | Errors occurred!
  |   [test_execution_error] Test "avg_length > 3" failed
  | Exiting with code 1
```

YAML2
```
columns:
  feepct:
    tests:
      - avg_length == 3
```

OUTPUT2
```
  | Test error for "avg_length == 3": name 'avg_length' is not defined
  | Executed 2 queries in 0:00:00.025654
  | Scan summary ------
  | 40 measurements computed
  | 1 tests executed
  | 1 of 1 tests failed:
  |   Test column(feepct) test(avg_length == 3) failed with metric values null
  | Errors occurred!
  |   [test_execution_error] Test "avg_length == 3" failed
  | Exiting with code 1
```

YAML3
```
metric_groups:
  - profiling
tests:
  - row_count > 1
columns:
  name:
    tests:
     - avg_length
```

OUTPUT3
```
  | Test test(row_count > 1) passed with metric values {"row_count": 65}
  | Test error for "avg_length": name 'avg_length' is not defined
  | Executed 16 queries in 0:00:00.070503
  | Scan summary ------
  | 54 measurements computed
  | 2 tests executed
  | 1 of 2 tests failed:
  |   Test column(name) test(avg_length) failed with metric values null
  | Errors occurred!
  |   [test_execution_error] Test "avg_length" failed
  | Exiting with code 1
```

YAML4
```
tests:
  - row_count > 1
columns:
  id:
    tests:
     - avg_length
```

OUTPUT4
```
  | Test test(row_count > 1) passed with metric values {"row_count": 65}
  | Test error for "avg_length": name 'avg_length' is not defined
  | Executed 2 queries in 0:00:00.026360
  | Scan summary ------
  | 40 measurements computed
  | 2 tests executed
  | 1 of 2 tests failed:
  |   Test column(id) test(avg_length) failed with metric values null
  | Errors occurred!
  |   [test_execution_error] Test "avg_length" failed
  | Exiting with code 1
```

**OS**:  MacOS Big Sur 11.2.3
**Python Version**: 3.8.8
**Soda SQL Version**: 2.1.0b1
**Warehouse Type**: PostgreSQL
