### ISSUE TITLE
Custom SQL Column Metrics are pushed to server as "Dataset Metrics"

### ISSUE THREAD

**Issue by dirkgroenen** [sodadata/soda-sql#190]
**Describe the bug**
I've got an `orders.yml` with some custom SQL Metrics at Column level. When running a `soda scan` I would expect those to be pushed to the Soda Cloud as Column Metrics, but instead they are stored as Dataset Metrics.

See the following request which is being made during my scan: 

```
  | SQL took 0:00:00.101114
  | SQL metric O_ORDERSTATUS.sql_metric[0] ORDER_P -> 38543
  | Query measurement: ORDER_P = 38543
  | SQL metric O_ORDERSTATUS.sql_metric[0] ORDER_O -> 732044
  | Query measurement: ORDER_O = 732044
  | > /api/command {
  "type": "sodaSqlScanMeasurements",
  "scanReference": "733c5416-df7c-4917-8e8c-f0a5559a3a0d",
  "measurements": [
    {
      "metric": "ORDER_P",
      "value": 38543
    },
    {
      "metric": "ORDER_O",
      "value": 732044
    }
  ]
}
```

As you can see the `orders.yml` defines the SQL metrics at 'column level', which means I would expect those measurements to come in as 'order metric' measurements:

```yml
table_name: ORDERS
metrics:
  - ...
columns:
  O_TOTALPRICE:
    sql_metrics:
      - sql: |
          SELECT SUM(O_TOTALPRICE) as OPEN_TOTALPRICE FROM ORDERS WHERE O_ORDERSTATUS = 'O'
        tests:
          open_orders_price: OPEN_TOTALPRICE < 2000000

  O_ORDERSTATUS:
    valid_values:
      - O
      - F
    sql_metrics:
      - sql: |
          SELECT
            COUNT(CASE WHEN O_ORDERSTATUS = 'P' THEN 1 END) as ORDER_P,
            COUNT(CASE WHEN O_ORDERSTATUS = 'O' THEN 1 END) as ORDER_O
          FROM ORDERS
        tests:
          open_orders: ORDER_O == 0
          processing_orders: ORDER_P > 0
```

**OS**: 
**Python Version**:
**Soda SQL Version**: https://github.com/sodadata/soda-sql/commit/7eb40213edf9e26e87629169a27634e6be9f55ee
**Warehouse Type**: Snowflake
