### ISSUE TITLE
Added sampling, failed and passing rows configuration

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-sql#197]
Adding following configs to the scan yaml config:

```
samples:
    table_limit: int
    table_tablesample: str
    failed_limit: int
    failed_tablesample: str
    passed_limit: int
    passed_tablesample: int

columns:
    some_column_name:
        samples:
            failed_limit: int
            failed_tablesample: str
            passed_limit: int
            passed_tablesample: int    
```

Samples will only be taken and send to soda cloud if soda cloud is configured in the warehouse yaml file.

The `..._limit` properties will append a `LIMIT {configured_value}` to the SQL that is used to take the sample
The `..._tablesample` properties will append a `TABLESAMPLE {configured_tablesample_value}` to the SQL that is used to take the sample

If either `table_limit` or `table_tablesample` is specified (mutually exclusive), a table sample will be taken with the specified property.

The `failed_...` and `passed_...` properties on the scan top level serve to specify default values.

Samples will only be taken if the respective metrics indicate that at least 1 row is to be expected.  The user is responsible to ensure that the metrics are computed.  The Soda scan YAML parser will **not** automatically add the metric in case the sample configurations are specified.

If either `table_limit` or `table_tablesample` is specified (mutually exclusive), a table sample will be taken with the specified property.  The metric used is the `row_count`.

If `failed_limit` or `failed_tablesample` are specified **and** metrics `missing_count` or `invalid_count` are greater than 0, than a sample will be taken and sent to Soda Cloud.   Similar for `passed_limit` or `passed_tablesample` with metrics `values_count` or `valid_count`
