### ISSUE TITLE
More complex expression in test confuses the counter

### ISSUE THREAD

**Issue by vonkad** [sodadata/soda-sql#239]
**Describe the bug**
My metrics section defines two table level sql metrics. My last test then combines these metrics with row_count. The actor table in the data set (the sample postgres dvdrental) has 200 rows. 113 of the actors have last name longer than first name and 60 vice versa. Exactly 27 actors have a first name with the same length as their last name. Anyway, the last test works. It will pass if I change the condition to 27 and fails if I make it 26. Just the reporting, as you see in the screenshot says that the value of the metrics is 200, which it is not. It should say 27.

```yaml
table_name: actor
metrics:
  - row_count
sql_metrics:
  - sql:
      select count(*) as long_name_count from actor where char_length(first_name)>char_length(last_name)
  - sql:
      select count(*) as long_surname_count from actor where char_length(first_name)<char_length(last_name)
tests:
  table_not_empty: row_count > 0
  "some people have first name longer than surname": long_name_count > 5
  "some people have first name shorter than surname": long_surname_count > 5
  "exactly 27 people have equal first and last name char count": row_count - long_name_count - long_surname_count == 26
columns:
  first_name:
    metrics:
      - invalid_percentage
      - min_length
      - avg_length
      - max_length
    valid_regex: ^[A-Z][a-z]+$
    tests:
      - invalid_percentage == 0
      - min_length > 1
```
Here goes the screenshot with the defect:
![image](https://user-images.githubusercontent.com/2754179/113493854-913b4600-94e3-11eb-9dab-fb22813cb2c2.png)

**Context**
__Include your scan.yml or warehouse.yml when relevant__

**OS**: Linux Miny
**Python Version**: 3.8
**Soda SQL Version**: 2.0.0b26
**Warehouse Type**: postgres
