### ISSUE TITLE
Seems like metrics gets lost when validating an iso date

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-sql#261]
**Describe the bug**
I have a number of tests defined (see config below) that works fine. But when I add an additional test for date format all other metrics seems to be lost. When I run the test the first time I see this:

```
| Sent sample demodata.size.invalid (3/3) to Soda Cloud
  | Executed 24 queries in 0:00:05.856183
  | Soda Cloud scan end ok
  | Scan summary ------
  | 111 measurements computed
  | 4 tests executed
  | All is good. No tests failed.
  | Exiting with code 0
```

But when I add this test:
```yml
date:
    valid_format: date_iso_8601
    tests:
        - invalid_percentage == 0
```
I get this result where all the existing tests are also failing.
```
  | Test error for "row_count > 0": name 'row_count' is not defined
  | Soda Cloud scan send test results
  | Test error for "invalid_percentage == 0": name 'invalid_percentage' is not defined
  | Test error for "invalid_percentage < 5": name 'invalid_percentage' is not defined
  | Test error for "invalid_percentage == 0": name 'invalid_percentage' is not defined
  | Test error for "invalid_percentage == 0": name 'invalid_percentage' is not defined
  | Soda Cloud scan send test results
  | Executed 1 queries in 0:00:01.436892
  | Soda Cloud scan end with errors
  | Scan summary ------
  | 1 measurements computed
  | 5 tests executed
  | 5 of 5 tests failed:
  |   Test test(row_count > 0) failed with metric values null
  |   Test column(id) test(invalid_percentage == 0) failed with metric values null
  |   Test column(size) test(invalid_percentage < 5) failed with metric values null
  |   Test column(date) test(invalid_percentage == 0) failed with metric values null
  |   Test column(feepct) test(invalid_percentage == 0) failed with metric values null
  | Errors occurred!
  |   [error] Exception during aggregation query
  |   [error] Exception during column group by value queries
  |   [error] Exception during column group by value queries
  |   [error] Exception during column group by value queries
  |   [error] Exception during column group by value queries
  |   [error] Exception during column group by value queries
  |   [error] Exception during column group by value queries
  |   [error] Exception during histogram query for size
  |   [error] Exception during histogram query for feepct
  |   [test_execution_error] Test "row_count > 0" failed
  |   [test_execution_error] Test "invalid_percentage == 0" failed
  |   [test_execution_error] Test "invalid_percentage < 5" failed
  |   [test_execution_error] Test "invalid_percentage == 0" failed
  |   [test_execution_error] Test "invalid_percentage == 0" failed
  | Exiting with code 1
```

**To Reproduce**
1. Use an existing test config like:
```yml
table_name: demodata
metrics:
  - row_count
  - missing_count
  - missing_percentage
  - values_count
  - values_percentage
  - valid_count
  - valid_percentage
  - invalid_count
  - invalid_percentage
  - min_length
  - max_length
  - avg_length
  - min
  - max
  - avg
  - sum
  - variance
  - stddev
  - histogram
  - uniqueness
samples:
  table_limit: 10
  failed_limit: 10
tests:
  - row_count > 0
columns:
  id:
    valid_format: uuid
    tests:
      - invalid_percentage == 0
  feepct:
    valid_format: number_percentage
    tests:
      - invalid_percentage == 0
  size:
    valid_max: 9800
    tests:
      - invalid_percentage < 5
```
2. Run `soda scan ...`
3  Add this test:
```yml
date:
    valid_format: date_iso_8601
    tests:
        - invalid_percentage == 0
```
4. Run `soda scan ...` again.

**Context**
__Include your scan.yml or warehouse.yml when relevant__

**OS**: Mac OS 11.2.3
**Python Version**: 3.9.2
**Soda SQL Version**: 2.1.0b1
**Warehouse Type**: postgres
