### ISSUE TITLE
'row_count' is not defined

### ISSUE THREAD

**Issue by puruzio** [sodadata/soda-sql#267]
**Describe the bug**
In Scan YAML, adding multiple metrics seems to cause an error.

**To Reproduce**
1. Create a new test in `scan.yml`
2. Run `soda scan ...`
3. scan fails when multiple metrics specified, resulting in the following error message. 
```
  | Test error for "row_count > 0": name 'row_count' is not defined
  | Test error for "invalid_count > 10": name 'invalid_count' is not defined
```
**Context**
__Include your scan.yml or warehouse.yml when relevant__

For example, this works:

```
table_name: Clients
metrics:
  - row_count
tests:
  - row_count > 0

```
But this fails:
```
table_name: Clients
metrics:
  - row_count
  - invalid_count
tests:
  - row_count > 0
columns:
  client:
    valid_format: number_whole
    tests:
      - invalid_count > 10
```

**OS**:  Windows 10
**Python Version**:  3.75
**Soda SQL Version**:  2.1.0b1
**Warehouse Type**: SQLSERVER

**Comment by janet-can** [comment]
Since I've been testing a bunch of metrics in tests today, I'll just add my 2¢:

I encountered similar issues though it seemed the errors were thrown only when I used `valid_format: number_whole`. If I had to guess, I would say it was maybe the `valid_format` value throwing things off.

For example, this worked as expected:
```
tests:
  - row_count > 0
columns:
  id:
    valid_format: uuid
    tests:
      - invalid_count > 10
```
     
```shell
  | Test test(row_count > 0) passed with metric values {"row_count": 65}
  | Test column(id) test(invalid_count < 10) passed with metric values {"invalid_count": 0}
  | Executed 2 queries in 0:00:00.029796
  | Scan summary ------
  | 44 measurements computed
  | 2 tests executed
  | All is good. No tests failed.
  | Exiting with code 0
```

But this threw an error:
```
tests:
  - row_count > 0
columns:
  size:
    valid_format: number_whole
    tests:
      - invalid_count > 10
```

```
  | Test error for "row_count > 0": name 'row_count' is not defined
  | Test error for "invalid_count > 10": name 'invalid_count' is not defined
  | Executed 1 queries in 0:00:00.022948
  | Scan summary ------
  | 1 measurements computed
  | 2 tests executed
  | 2 of 2 tests failed:
  |   Test test(row_count > 0) failed with metric values null
  |   Test column(size) test(invalid_count > 10) failed with metric values null
  | Errors occurred!
  |   [error] Exception during aggregation query
  |   [test_execution_error] Test "row_count > 0" failed
  |   [test_execution_error] Test "invalid_count > 10" failed
  | Exiting with code 1
```

**OS:** Big Sur 11.2.3
**Python version:** 3.8.8
**Soda SQL version:** 2.1.0b1
**Warehouse Type:** PostgreSQL
**schema**: 
``` 
{"schema": [{"name": "id", "type": "character varying"}, {"name": "name", "type": "character varying"}, {"name": "size", "type": "integer"}, {"name": "date", "type": "date"}, {"name": "feepct", "type": "character varying"}, {"name": "country", "type": "character varying"}]}
```

**Comment by janet-can** [comment]
Adding a few more oddities that I think are related.

**1. min**
I expect to be able to use an operand with the `min` metric, no?
YAML
```columns:
  feepct:
    tests:
      - min < 5
 ```
OUTPUT
```
  | Test error for "min < 5": '<' not supported between instances of 'builtin_function_or_method' and 'int'
  | Executed 2 queries in 0:00:00.036505
  | Scan summary ------
  | 40 measurements computed
  | 1 tests executed
  | 1 of 1 tests failed:
  |   Test column(feepct) test(min < 5) failed with metric values null
  | Errors occurred!
  |   [test_execution_error] Test "min < 5" failed
  | Exiting with code 1
```

YAML
```
columns:
  feepct:
    tests:
      - min > 5
```

OUTPUT
```
  | Test error for "min > 5": '>' not supported between instances of 'builtin_function_or_method' and 'int'
  | Executed 2 queries in 0:00:00.026750
  | Scan summary ------
  | 40 measurements computed
  | 1 tests executed
  | 1 of 1 tests failed:
  |   Test column(feepct) test(min > 5) failed with metric values null
  | Errors occurred!
  |   [test_execution_error] Test "min > 5" failed
  | Exiting with code 1
```


YAML

```columns:
  feepct:
    tests:
      - min == 5
```

OUTPUT
```
  | Test column(feepct) test(min == 5) failed with metric values {}
  | Executed 2 queries in 0:00:00.032092
  | Scan summary ------
  | 40 measurements computed
  | 1 tests executed
  | 1 of 1 tests failed:
  |   Test column(feepct) test(min == 5) failed with metric values {}
  | Exiting with code 1
```


YAML
```
columns:
  feepct:
    tests:
      - min
```

OUTPUT
```
  | Test column(feepct) test(min) passed with metric values {}
  | Executed 2 queries in 0:00:00.031856
  | Scan summary ------
  | 40 measurements computed
  | 1 tests executed
  | All is good. No tests failed.
  | Exiting with code 0
```

**2. avg_length**
I expect to be able to use an operand with `avg_length`, no?
YAML
```
columns:
  feepct:
    tests:
      - avg_length > 3
```

OUTPUT
```
  | Test error for "avg_length > 3": name 'avg_length' is not defined
  | Executed 2 queries in 0:00:00.039690
  | Scan summary ------
  | 40 measurements computed
  | 1 tests executed
  | 1 of 1 tests failed:
  |   Test column(feepct) test(avg_length > 3) failed with metric values null
  | Errors occurred!
  |   [test_execution_error] Test "avg_length > 3" failed
  | Exiting with code 1
```

YAML
```
columns:
  feepct:
    tests:
      - avg_length == 3
```

OUTPUT
```
  | Test error for "avg_length == 3": name 'avg_length' is not defined
  | Executed 2 queries in 0:00:00.025654
  | Scan summary ------
  | 40 measurements computed
  | 1 tests executed
  | 1 of 1 tests failed:
  |   Test column(feepct) test(avg_length == 3) failed with metric values null
  | Errors occurred!
  |   [test_execution_error] Test "avg_length == 3" failed
  | Exiting with code 1
```

**3. values_count**
It seems like it's not picking up the values I specify as valid. Test1 specifies `US` and returns 65 instances (also the total row count).  Test2 specifies `UK` and it also returns 65 instances. Hmmm.
YAML
```
tests:
  - row_count
columns:
  country:
    valid_values: 
      - US
    tests:
      - values_count > 1
```

OUTPUT
```
  | Test test(row_count) passed with metric values {"row_count": 65}
  | Test column(country) test(values_count > 1) passed with metric values {"values_count": 65}
  | Executed 2 queries in 0:00:00.028942
  | Scan summary ------
  | 44 measurements computed
  | 2 tests executed
  | All is good. No tests failed.
  | Exiting with code 0
```
YAML
```
tests:
  - row_count
columns:
  country:
    valid_values: 
      - UK
    tests:
      - values_count > 1
```

OUTPUT
```
  | Test test(row_count) passed with metric values {"row_count": 65}
  | Test column(country) test(values_count > 1) passed with metric values {"values_count": 65}
  | Executed 2 queries in 0:00:00.028288
  | Scan summary ------
  | 44 measurements computed
  | 2 tests executed
  | All is good. No tests failed.
  | Exiting with code 0
```
