### ISSUE TITLE
Snowflake sql metrics

### ISSUE THREAD

**Issue by N214** [sodadata/soda-sql#272]
**Describe the bug**
SQL metrics on snowflake yield, name 'sum_avail_bikes' is not defined

**To Reproduce**
1. Table file:
```
table_name: RAW_VILLO_FLAT
sql_metrics:
  - sql: |
      SELECT sum(AVAILABLE_BIKE_STANDS) as sum_avail_bikes
      from RAW_VILLO_FLAT
    tests:
      - sum_avail_bikes > 1

```
2. `soda scan ....`
3. Output
```
SELECT sum(AVAILABLE_BIKE_STANDS) as sum_avail_bikes
from RAW_VILLO_FLAT

  | SQL took 0:00:00.188308
  | SQL metric sql_metric[0] SUM_AVAIL_BIKES -> 18735097
  | Query measurement: SUM_AVAIL_BIKES = 18735097
  | Soda Cloud scan send measurements
  | Test error for "sum_avail_bikes > 1": name 'sum_avail_bikes' is not defined
  | Soda Cloud scan send test results
  | Executed 2 queries in 0:00:03.053959
  | Soda Cloud scan end with errors
  | Scan summary ------
  | 2 measurements computed
  | 1 tests executed
  | 1 of 1 tests failed:
  |   Test sqlmetric(0) test(sum_avail_bikes > 1) failed with metric values null
  | Errors occurred!
  |   [test_execution_error] Test "sum_avail_bikes > 1" failed
  | Exiting with code 1
```
**Solution**
Put everything in capital letters
1. Table file:
```
table_name: RAW_VILLO_FLAT
sql_metrics:
  - sql: |
      SELECT sum(AVAILABLE_BIKE_STANDS) as sum_avail_bikes
      from RAW_VILLO_FLAT
    tests:
      - SUM_AVAIL_BIKES > 1
```
2. `soda scan ....`
3. Output
```
SELECT sum(AVAILABLE_BIKE_STANDS) as sum_avail_bikes
from RAW_VILLO_FLAT

  | SQL took 0:00:00.496483
  | SQL metric sql_metric[0] SUM_AVAIL_BIKES -> 18735097
  | Query measurement: SUM_AVAIL_BIKES = 18735097
  | Soda Cloud scan send measurements
  | Test sqlmetric(0) test(SUM_AVAIL_BIKES > 1) passed with metric values {"SUM_AVAIL_BIKES": 18735097}
  | Soda Cloud scan send test results
  | Executed 2 queries in 0:00:02.949532
  | Soda Cloud scan end ok
  | Scan summary ------
  | 2 measurements computed
  | 1 tests executed
  | All is good. No tests failed.
  | Exiting with code 0
```

**Remarks**
The bug does not exist with Postgres, have not tested with other warehouses

**OS**: Manjaro Linux 
**Python Version**: 3.7.0
**Soda SQL Version**:  2.0.0b27
**Warehouse Type**: Snowflake
