### ISSUE TITLE
Test required columns

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-sql#275]
Enhance the ability to test required columns

Every column that is specified in the scan YAML should exist.  If not the scan should fail with a message but still compute all the other measurments/tests

Eg 

```
columns:
  id:
    type: VARCHAR(255)
  size:
  amount:
```

Will test if id is present and has type `VARCHAR(255)`
And it will test that columns `size` and `amount` are present no matter which data type.

This form of required column testing works with and without Soda Cloud configured.
