### ISSUE TITLE
Unexpected behavior of some metrics

### ISSUE THREAD

**Issue by janet-can** [sodadata/soda-sql#280]
**Describe the bug**
During the process of testing each metric to confirm which data type is works with (number, text, date), I encountered some behaviors that were unexpected. Detailed list below.

Also, a few questions about usage:
a. Does the configuration key `valid_min_length` not apply to `min_length` metric?
b. Does the configuration key `valid_max_length` not apply to `max_length` metric?
c. How does one use the `missing_format` configuration key? What are the expected values for that key?
d. What does one use `valid_min` and `valid_max` for in a text column? (Doesn't `valid_min_length` and `valid_max_length` fulfill the valid parameters?

**To Reproduce**
I was using the Demodata warehouse that is part of the Quick start tutorial so can reproduce all issues using that db. For reference, the schema is:
[{"name": "id", 	"type": "character varying"}, 
{"name": "name", 	"type": "character varying"}, 
{"name": "size", 	"type": "integer"}, 
{"name": "date", 	"type": "date"}, 
{"name": "feepct", "type": "character varying"}, 
{"name": "country","type": "character varying"}]}

**Context**

1. Why do the tests on the `size` and `date` columns pass? Pass by default if no `valid_values` defined? (The test that fails is accurate.)
```yaml
columns:
  id:
    valid_format: number_whole
    tests:
      - invalid_count == 0
  size:
    tests:
      - invalid_count == 0
  date:
    tests:
      - invalid_count == 0
```
```shell
  | Test column(id) test(invalid_count == 0) failed with metric values {"invalid_count": 65}
  | Test column(size) test(invalid_count == 0) passed with metric values {"invalid_count": 0}
  | Test column(date) test(invalid_count == 0) passed with metric values {"invalid_count": 0}
  | Executed 2 queries in 0:00:00.034919
  | Scan summary ------
  | 74 measurements computed
  | 3 tests executed
  | 1 of 3 tests failed:
  |   Test column(id) test(invalid_count == 0) failed with metric values {"invalid_count": 65}
  | Exiting with code 1
```
2. What is `missing_count` counting if I have not provided a definition of what qualifies as missing?
```yaml
columns:
  id:
    tests:
      - missing_count == 0
  size:
    tests:
      - missing_count == 0
  date:
    tests:
      - missing_count == 0
```
```shell
  | Test column(id) test(missing_count == 0) passed with metric values {"missing_count": 0}
  | Test column(size) test(missing_count == 0) passed with metric values {"missing_count": 0}
  | Test column(date) test(missing_count == 0) passed with metric values {"missing_count": 0}
  | Executed 2 queries in 0:00:00.034437
  | Scan summary ------
  | 68 measurements computed
  | 3 tests executed
  | All is good. No tests failed.
  | Exiting with code 0
```

3. If I haven't specified a `valid_format` for the `id` column (a text column)  shouldn't the test fail?  Shouldn't all three tests fail here?
```yaml
columns:
  id:
    tests:
      - valid_count > 1
  size:
    tests:
      - valid_count > 1
  date:
    tests:
      - valid_count > 1
```
```shell
  | Test column(id) test(valid_count > 1) passed with metric values {"valid_count": 65}
  | Test column(size) test(valid_count > 1) passed with metric values {"valid_count": 65}
  | Test column(date) test(valid_count > 1) passed with metric values {"valid_count": 65}
  | Executed 2 queries in 0:00:00.041611
  | Scan summary ------
  | 68 measurements computed
  | 3 tests executed
  | All is good. No tests failed.
  | Exiting with code 0
```

4. If I haven't specified a `valid_values ` for the `id` column (a text column)  shouldn't the test fail?  Shouldn't all three tests fail here?
```yaml
columns:
  country:
    tests:
      - values_count > 1
  size:
    tests:
      - values_count > 1
  date:
    tests:
      - values_count > 1
```

```shell
  | Test column(size) test(values_count > 1) passed with metric values {"values_count": 65}
  | Test column(date) test(values_count > 1) passed with metric values {"values_count": 65}
  | Test column(country) test(values_count > 1) passed with metric values {"values_count": 65}
  | Executed 2 queries in 0:00:00.043434
  | Scan summary ------
  | 68 measurements computed
  | 3 tests executed
  | All is good. No tests failed.
  | Exiting with code 0
```

**OS**: MacOS Big Sur 11.2.3
**Python Version**: 3.8.8
**Soda SQL Version**: 2.1.0b2
**Warehouse Type**: PostgreSQL
