### ISSUE TITLE
Custom SQL metric isn't casting to handle the correct semantic type

### ISSUE THREAD

**Issue by dirkgroenen** [sodadata/soda-sql#330]
I'm evaluating a Custom Metric in Soda SQL which is provided by Soda Cloud, but it seems like the column's semantic type isn't taken into account correctly. 

Take a look at the following filter expression, especially look at the `maturity` column: 

```jsonc
{
  "type": "and",
  "andExpressions": [
    {
      "type": "not",
      "expression": {
        "type": "equals",
        "left": {
          "type": "columnValue",
          "columnName": "asset_status"
        },
        "right": {
          "type": "string",
          "value": "INACTIVE"
        }
      }
    },
    {
      "type": "startsWith",
      "left": {
        "type": "columnValue",
        "columnName": "reviewed_by"
      },
      "right": {
        "type": "string",
        "value": "i7"
      }
    },
    {
      "type": "or",
      "orExpressions": [
        {
          "type": "greaterThanOrEqual",
          "left": {
            "type": "columnValue",
            "columnName": "maturity"
          },
          "right": {
            "type": "time",
            "scanTime": true
          }
        },
        {
          "type": "equals",
          "left": {
            "type": "columnValue",
            "columnName": "maturity"
          },
          "right": {
            "type": "null"
          }
        }
      ]
    },
    {
      "type": "equals",
      "left": {
        "type": "columnValue",
        "columnName": "cpn_type"
      },
      "right": {
        "type": "string",
        "value": "F"
      }
    },
    {
      "type": "not",
      "expression": {
        "type": "equals",
        "left": {
          "type": "columnValue",
          "columnName": "coupon_fix"
        },
        "right": {
          "type": "number",
          "value": 0.0
        }
      }
    },
    {
      "type": "in",
      "left": {
        "type": "columnValue",
        "columnName": "sm_sec_group"
      },
      "right": {
        "type": "collection",
        "value": [
          "ABS",
          "BND",
          "CASH",
          "CMBS",
          "MBS",
          "IBND",
          "LOAN",
          "SYNTH"
        ]
      }
    },
    {
      "type": "not",
      "expression": {
        "type": "in",
        "left": {
          "type": "columnValue",
          "columnName": "sm_sec_type"
        },
        "right": {
          "type": "collection",
          "value": [
            "CASH",
            "SWAPTION"
          ]
        }
      }
    },
    {
      "type": "equals",
      "left": {
        "type": "columnValue",
        "columnName": "coup_freq"
      },
      "right": {
        "type": "null"
      }
    }
  ]
}
```

Ander consider the following scan YAML:

```yml
table_name: sm

metrics:
  - row_count

columns:
  issue_dt:
    valid_format: date_inverse
    tests:
      - invalid_percentage == 0
  adw_ingest_timestamp:
    valid_format: date_inverse
    tests:
      - invalid_percentage == 0
  maturity:
    valid_format: date_inverse
    tests:
      - invalid_percentage == 0
  first_pay_dt:
    valid_format: date_inverse
    tests:
      - invalid_percentage == 0
  client_f_id:
    valid_format: number_whole
    tests:
      - invalid_percentage == 0
```

It generates the following SQL query:

```sql
SELECT COUNT(*) 
FROM "soda_database"."sm" 
WHERE 
	NOT (asset_status = 'INACTIVE')
	AND (reviewed_by LIKE 'i7%') 
	AND ((maturity as date >= '2021-05-19T17:54:52+00:00') OR (maturity IS NULL)) 
	AND (cpn_type = 'F') 
	AND (NOT (coupon_fix = 0.0)) 
	AND (sm_sec_group IN ('ABS','BND','CASH','CMBS','MBS','IBND','LOAN','SYNTH')) 
	AND (NOT (sm_sec_type IN ('CASH','SWAPTION'))) 
	AND (coup_freq IS NULL)
```

As you can see the `maturity` column isn't casted as `DATE`, which makes the comparison fail. 

**The expected query** would be something like:
```sql
SELECT COUNT(*) 
FROM "soda_database"."sm" 
WHERE 
	NOT (asset_status = 'INACTIVE')
	AND (reviewed_by LIKE 'i7%') 
	AND ((cast(maturity as date) >= '2021-05-19T17:54:52+00:00') OR (maturity IS NULL)) 
	AND (cpn_type = 'F') 
	AND (NOT (coupon_fix = 0.0)) 
	AND (sm_sec_group IN ('ABS','BND','CASH','CMBS','MBS','IBND','LOAN','SYNTH')) 
	AND (NOT (sm_sec_type IN ('CASH','SWAPTION'))) 
	AND (coup_freq IS NULL)
```
