### ISSUE TITLE
Arithmetic Overflow Error in SQL Server

### ISSUE THREAD

**Issue by lucas-lm** [sodadata/soda-sql#351]
**Describe the bug**

Getting Overflow error for count validation.

![image](https://user-images.githubusercontent.com/29049644/170190265-a6e10349-9254-468b-aa5e-e8334290de95.png)

I guess it is related to the query that it is being running to perform the calculations. In SQL Server, regular counts and sum leads to Overflow error when not being applied to bigint, for example (count_big in case of the count).

**To Reproduce**
1. Create a new test in `tables/something.yml` for a big table
2. Run `soda scan tables/something.yml`

**Context**

```yml
table_name: big_table
metrics:
  - row_count
  - missing_count
  - values_count
  - sum
tests:
  - row_count > 0
```

**OS**: 
**Python Version**: Latest
**Soda SQL Version**: Latest
**Warehouse Type**: SQL Server
