### ISSUE TITLE
[bug] custom SQL Metrics don't seem to be read correctly

### ISSUE THREAD

**Issue by dirkgroenen** [sodadata/soda-sql#79]
**Describe the bug**
I was trying to create some custom SQL Metrics for demo purposes, but it seems like `soda scan` isn't able to resolve their path correctly. 

The output I'm seeying:

```
(...)
  | Scanning ORDERS in . ...
  | sql_metric_path scan.yml does not exist
  | sql_metric_path orderstatus_count.yml does not exist
  | Executing SQL query: 
```

It seems like the directory path is missing from the files, cause they are reported as 'missing'? 

**To Reproduce**
1. See my attached `scan.yml` and `orderstatus_count.yml` for an example of the setup
2. Run `soda scan . ORDERS` from within the project directory

**Context**
`scan.yml`
```yml
table_name: ORDERS
metrics:
  - row_count
  - missing_count
  - missing_percentage
  - values_count
  - values_percentage
  - invalid_count
  - invalid_percentage
  - min
  - max
  - avg
  - sum
tests:
  row_count_min: row_count > 0
```

`orderstatus_count.yml`
```yml
sql: |
  SELECT
    COUNT(CASE WHEN O_ORDERSTATUS IS "P" THEN 1 END) as order_p,
    COUNT(CASE WHEN O_ORDERSTATUS IS "O" THEN 1 END) as order_o,
  FROM ORDERS
tests:
  open_orders: order_o == 0
  processing_orders: order_p > 0
```
**OS**: Linux 5.10
**Python Version**: 3.8
**Soda SQL Version**: 2.0.0b6
**Warehouse Type**: Snowflake
