### ISSUE TITLE
Column names are always converted to uppercase

### ISSUE THREAD

**Issue by dirkgroenen** [sodadata/soda-sql#84]
**Describe the bug**
I've setup project which includes a custom SQL metric but I noticed the columns/variables are always converted or expected to be uppercase. 

Take for example the following SQL Metric:

```yml
sql: |
  SELECT
    COUNT(CASE WHEN O_ORDERSTATUS = 'P' THEN 1 END) as order_p,
    COUNT(CASE WHEN O_ORDERSTATUS = 'O' THEN 1 END) as order_o
  FROM ORDERS
tests:
  open_orders: order_o == 0
  processing_orders: order_p > 0
```

When running `soda scan` it produces the following output:

```
(...)
  | Executing SQL query: 
SELECT
  COUNT(CASE WHEN O_ORDERSTATUS = 'P' THEN 1 END) as order_p,
  COUNT(CASE WHEN O_ORDERSTATUS = 'O' THEN 1 END) as order_o
FROM ORDERS

  | SQL took 0:00:00.083167
  | SQL metric 0 ORDER_P -> 38543
  | Query measurement: ORDER_P = 38543
  | SQL metric 0 ORDER_O -> 732044
  | Query measurement: ORDER_O = 732044
  | Test table(ORDERS) expression(row_count == 0) failed
(...)
  | stddev(O_ORDERKEY) = 1732051.3849205659
  | ORDER_P = 38543
  | ORDER_O = 732044
  | 28 measurements computed
  | 3 tests executed
  | 3 of 3 tests failed:
  |   table(ORDERS) sql_metric(0) expression(order_o == 0) cause order_o=None
  |   table(ORDERS) sql_metric(0) expression(order_p > 0) cause order_p=None
  |   table(ORDERS) expression(row_count == 0) cause row_count=1500000
```

As you can see `order_p` and `order_o` have been converted to uppercase metrics, which causes my tests to fail. 

**To Reproduce**
1. Create a new SQL Meric and use lowercase metric/column names
2. Write some tests which utilize those, lowercase, metrics
3. Run `soda scan`
4. Expect the scan to fail because the metric values are `None`. 

**Context**
```yml
table_name: ORDERS
metrics:
  - row_count
  - sum
columns:
  O_ORDERSTATUS:
    valid_values:
      - O
      - F
sql_metrics:
  - sql: |
      SELECT
        COUNT(CASE WHEN O_ORDERSTATUS = 'P' THEN 1 END) as order_p,
        COUNT(CASE WHEN O_ORDERSTATUS = 'O' THEN 1 END) as order_o
      FROM ORDERS
    tests:
      open_orders: order_o == 0
      processing_orders: order_p > 0
tests:
  dataset_size: row_count == 0
```

**OS**:  Linux
**Python Version**: 3.8
**Soda SQL Version**: 2.0.0b8
**Warehouse Type**: Snowflake
